CREATE DATABASE IF NOT EXISTS ev_rental_db;
USE ev_rental_db;

CREATE TABLE MembershipPlans (
  PlanID INT AUTO_INCREMENT PRIMARY KEY,
  PlanName VARCHAR(50) NOT NULL,
  Cost DECIMAL(10, 2) NOT NULL,
  DurationMonths INT NOT NULL,
  Benefits TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Users (
  UserID INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(100) NOT NULL,
  Email VARCHAR(100) NOT NULL UNIQUE,
  Password VARCHAR(100) NOT NULL,
  Role ENUM('user', 'admin') NOT NULL DEFAULT 'user',
  WalletBalance DECIMAL(10, 2) DEFAULT 0.00,
  JoinDate DATE NOT NULL,
  PlanID INT,
  FOREIGN KEY (PlanID) REFERENCES MembershipPlans(PlanID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Stations (
  StationID INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(100) NOT NULL,
  Location VARCHAR(255) NOT NULL,
  Capacity INT NOT NULL,
  IsActive BOOLEAN NOT NULL DEFAULT TRUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Vehicles (
  VehicleID INT AUTO_INCREMENT PRIMARY KEY,
  RegistrationNumber VARCHAR(20) NOT NULL UNIQUE,
  Type VARCHAR(50) NOT NULL,
  Model VARCHAR(50) NOT NULL,
  Manufacturer VARCHAR(50) NOT NULL,
  RatePerHour DECIMAL(10, 2) NOT NULL,
  Status ENUM('available', 'in-use', 'under-maintenance', 'decommissioned') NOT NULL DEFAULT 'available',
  CurrentStationID INT,
  FOREIGN KEY (CurrentStationID) REFERENCES Stations(StationID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Trips (
  TripID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  VehicleID INT NOT NULL,
  StartStationID INT NOT NULL,
  EndStationID INT,
  StartTime DATETIME NOT NULL,
  EndTime DATETIME,
  Cost DECIMAL(10, 2) NOT NULL,
  Status ENUM('Upcoming', 'Ongoing', 'Completed', 'Cancelled') NOT NULL DEFAULT 'Upcoming',
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (VehicleID) REFERENCES Vehicles(VehicleID),
  FOREIGN KEY (StartStationID) REFERENCES Stations(StationID),
  FOREIGN KEY (EndStationID) REFERENCES Stations(StationID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Payments (
  PaymentID INT AUTO_INCREMENT PRIMARY KEY,
  TripID INT,
  UserID INT NOT NULL,
  Amount DECIMAL(10, 2) NOT NULL,
  Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Status VARCHAR(20) NOT NULL,
  FOREIGN KEY (TripID) REFERENCES Trips(TripID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Technicians (
  TechnicianID INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(100) NOT NULL,
  Specialization VARCHAR(100) NOT NULL,
  IsAvailable BOOLEAN NOT NULL DEFAULT TRUE,
  ActiveAssignments INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE MaintenanceLogs (
  LogID INT AUTO_INCREMENT PRIMARY KEY,
  VehicleID INT NOT NULL,
  IssueReported TEXT NOT NULL,
  ReportedDate DATE NOT NULL,
  Status VARCHAR(50) NOT NULL DEFAULT 'Pending',
  FOREIGN KEY (VehicleID) REFERENCES Vehicles(VehicleID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE TechnicianAssignments (
  AssignmentID INT AUTO_INCREMENT PRIMARY KEY,
  LogID INT NOT NULL,
  TechnicianID INT NOT NULL,
  UNIQUE(LogID, TechnicianID),
  FOREIGN KEY (LogID) REFERENCES MaintenanceLogs(LogID),
  FOREIGN KEY (TechnicianID) REFERENCES Technicians(TechnicianID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Reviews (
  ReviewID INT AUTO_INCREMENT PRIMARY KEY,
  TripID INT NOT NULL,
  UserID INT NOT NULL,
  VehicleID INT NOT NULL,
  Rating INT NOT NULL,
  Comment TEXT,
  ReviewDate DATE NOT NULL,
  FOREIGN KEY (TripID) REFERENCES Trips(TripID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (VehicleID) REFERENCES Vehicles(VehicleID),
  UNIQUE KEY uq_user_trip (UserID, TripID),
  INDEX idx_vehicle (VehicleID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
